package com.studentmanagement.utility;
import com.studentmanagement.exception.InvalidDataException; import java.io.*; import java.nio.charset.StandardCharsets; import java.nio.file.*; import java.util.*;
/** Small CSV helper. Fields are validated to exclude commas, keeping the format teachable. */
public final class FileManager {
    private FileManager(){}
    public static List<String[]> readCsv(Path file,int columns){ensure(file);List<String[]> rows=new ArrayList<>();try(InputStream in=new FileInputStream(file.toFile());BufferedReader reader=new BufferedReader(new InputStreamReader(in,StandardCharsets.UTF_8))){String line;while((line=reader.readLine())!=null){if(line.isBlank()||line.startsWith("#"))continue;String[] parts=line.split(",",-1);if(parts.length==columns)rows.add(parts);}}catch(IOException|NumberFormatException e){throw new InvalidDataException("Could not read "+file+": "+e.getMessage());}return rows;}
    public static void writeCsv(Path file,Collection<String[]> rows){ensure(file);Path temp=file.resolveSibling(file.getFileName()+".tmp");try(OutputStream out=new FileOutputStream(temp.toFile());BufferedWriter writer=new BufferedWriter(new OutputStreamWriter(out,StandardCharsets.UTF_8))){for(String[] row:rows){writer.write(String.join(",",row));writer.newLine();}}catch(IOException e){throw new InvalidDataException("Could not write "+file+": "+e.getMessage());}try{Files.move(temp,file,StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){try{Files.move(temp,file,StandardCopyOption.REPLACE_EXISTING);}catch(IOException x){throw new InvalidDataException("Could not replace "+file+": "+x.getMessage());}}catch(IOException e){throw new InvalidDataException("Could not replace "+file+": "+e.getMessage());}}
    private static void ensure(Path file){try{Path parent=file.toAbsolutePath().getParent();if(parent!=null)Files.createDirectories(parent);if(Files.notExists(file))Files.createFile(file);}catch(IOException e){throw new InvalidDataException("Could not create "+file+": "+e.getMessage());}}
}
