package com.studentmanagement.ui;
import com.studentmanagement.model.*; import com.studentmanagement.repository.AcademicRepository; import com.studentmanagement.service.*; import com.studentmanagement.utility.GradeCalculator; import java.util.*;
/** Terminal UI. Business rules deliberately remain in the service layer. */
public class ConsoleMenu {
    private final Scanner in=new Scanner(System.in); private final StudentService students; private final CourseService courses; private final EnrollmentService enrollments; private final ReportService reports; private final AcademicRepository repository;
    public ConsoleMenu(StudentService s,CourseService c,EnrollmentService e,ReportService r,AcademicRepository repo){students=s;courses=c;enrollments=e;reports=r;repository=repo;}
    public void run(){boolean running=true;while(running){header("STUDENT ACADEMIC MANAGEMENT SYSTEM");System.out.println("1. Student Management\n2. Course Management\n3. Enrollment Management\n4. Marks Management\n5. Attendance Management\n6. Reports & Analytics\n7. Save Data\n8. Exit");switch(number("Enter choice: ")){case 1->studentMenu();case 2->courseMenu();case 3->enrollmentMenu();case 4->marks();case 5->attendance();case 6->reportMenu();case 7->{students.save();repository.save();System.out.println("Data saved.");}case 8->running=false;default->System.out.println("ERROR: Choose 1-8.");}}students.save();repository.save();System.out.println("Data saved. Goodbye!");}
    private void studentMenu(){boolean back=false;while(!back){header("STUDENT MANAGEMENT");System.out.println("1. Add\n2. View\n3. Update\n4. Delete\n5. Search by name\n6. View all\n7. Sort\n8. Back");try{switch(number("Choice: ")){case 1->System.out.println("Added: "+students.add(text("ID: "),text("Name: "),text("Email: "),text("Department: "),number("Semester: ")).displayDetails());case 2->System.out.println(students.find(text("ID: ")).displayDetails());case 3->System.out.println("Updated: "+students.update(text("ID: "),text("Name: "),text("Email: "),text("Department: "),number("Semester: ")).displayDetails());case 4->{String id=text("ID: ");students.delete(id);repository.removeStudentData(id);System.out.println("Student deleted.");}case 5->printStudents(students.searchByName(text("Partial name: ")));case 6->printStudents(students.all());case 7->sortStudents();case 8->back=true;default->System.out.println("ERROR: Choose 1-8.");}}catch(RuntimeException e){error(e);}}}
    private void sortStudents(){System.out.println("1. ID  2. Name  3. Average marks  4. Attendance");int n=number("Sort by: ");if(n==3||n==4){List<ReportService.StudentMetric> list=new ArrayList<>(reports.topPerformers());if(n==4)list.sort(Comparator.comparingDouble(ReportService.StudentMetric::attendance).reversed());list.forEach(m->System.out.printf("%s | average %.2f | attendance %.2f%%%n",m.student().displayDetails(),m.average(),m.attendance()));return;}List<Student> list=new ArrayList<>(students.all());if(n==1)Collections.sort(list);else if(n==2)list.sort(Comparator.comparing(Student::getName,String.CASE_INSENSITIVE_ORDER));else{System.out.println("ERROR: Choose 1-4.");return;}printStudents(list);}
    private void courseMenu(){boolean back=false;while(!back){header("COURSE MANAGEMENT");System.out.println("1. Create\n2. Update\n3. Delete\n4. View\n5. View all\n6. Search\n7. Back");try{switch(number("Choice: ")){case 1->System.out.println("Created: "+readCourse(false));case 2->System.out.println("Updated: "+readCourse(true));case 3->{courses.delete(text("Code: "));System.out.println("Course deleted.");}case 4->System.out.println(courses.find(text("Code: ")));case 5->courses.all().stream().sorted(Comparator.comparing(Course::getName)).forEach(System.out::println);case 6->courses.search(text("Code/name: ")).forEach(System.out::println);case 7->back=true;default->System.out.println("ERROR: Choose 1-7.");}}catch(RuntimeException e){error(e);}}}
    private Course readCourse(boolean update){String code=text("Code: "),name=text("Name: ");int credits=number("Credits: ");String faculty=text("Faculty: ");int max=number("Maximum marks: ");return update?courses.update(code,name,credits,faculty,max):courses.add(code,name,credits,faculty,max);}
    private void enrollmentMenu(){boolean back=false;while(!back){header("ENROLLMENT MANAGEMENT");System.out.println("1. Enroll\n2. Remove enrollment\n3. View student's courses\n4. View course's students\n5. Back");try{switch(number("Choice: ")){case 1->{enrollments.enroll(text("Student ID: "),text("Course code: "));System.out.println("Enrollment created.");}case 2->{enrollments.remove(text("Student ID: "),text("Course code: "));System.out.println("Enrollment removed.");}case 3->enrollments.coursesFor(text("Student ID: ")).forEach(System.out::println);case 4->printStudents(enrollments.studentsFor(text("Course code: ")));case 5->back=true;default->System.out.println("ERROR: Choose 1-5.");}}catch(RuntimeException e){error(e);}}}
    private void marks(){try{String s=text("Student ID: "),c=text("Course code: ");enrollments.recordMarks(s,c,decimal("Assignment (0-20): "),decimal("Midterm (0-30): "),decimal("Final (0-50): "));AcademicRecord r=repository.record(s,c).orElseThrow();System.out.printf("Saved. Total %.2f/100, grade %s%n",r.total(),GradeCalculator.calculate(r.total()));}catch(RuntimeException e){error(e);}}
    private void attendance(){try{String s=text("Student ID: "),c=text("Course code: ");enrollments.recordAttendance(s,c,number("Classes conducted: "),number("Classes attended: "));AcademicRecord r=repository.record(s,c).orElseThrow();System.out.printf("Saved. Attendance %.2f%% — %s%n",r.attendancePercentage(),r.attendancePercentage()<75?"LOW ATTENDANCE":"SATISFACTORY");}catch(RuntimeException e){error(e);}}
    private void reportMenu(){header("REPORTS & ANALYTICS");System.out.println("1. Student academic report\n2. Top performers\n3. Low attendance\n4. Failed subjects\n5. Course performance");try{switch(number("Choice: ")){case 1->studentReport(text("Student ID: "));case 2->reports.topPerformers().forEach(m->System.out.printf("%s | average %.2f%%%n",m.student().getName(),m.average()));case 3->reports.lowAttendance().forEach(m->System.out.printf("%s | %.2f%%%n",m.student().getName(),m.attendance()));case 4->reports.failed().forEach(r->System.out.printf("%s | %s | %.2f | F%n",r.getStudentId(),r.getCourseCode(),r.total()));case 5->reports.coursePerformance().forEach(m->System.out.printf("%s | enrolled %d | high %.2f | low %.2f | avg %.2f | pass %d | fail %d%n",m.course().getCode(),m.enrolled(),m.highest(),m.lowest(),m.average(),m.passed(),m.failed()));default->System.out.println("ERROR: Choose 1-5.");}}catch(RuntimeException e){error(e);}}
    private void studentReport(String id){Student s=students.find(id);header("ACADEMIC REPORT");System.out.println(s.displayDetails());for(AcademicRecord r:reports.recordsFor(id))System.out.printf("%s | marks %.2f | grade %s | attendance %.2f%%%s%n",r.getCourseCode(),r.total(),GradeCalculator.calculate(r.total()),r.attendancePercentage(),r.attendancePercentage()<75?" | LOW":"");System.out.printf("Overall average: %.2f%%%n",reports.average(id));}
    private void printStudents(Collection<Student> list){if(list.isEmpty())System.out.println("No students found.");else list.forEach(s->System.out.println(s.displayDetails()));}
    private String text(String prompt){System.out.print(prompt);return in.nextLine().trim();} private int number(String p){while(true){try{return Integer.parseInt(text(p));}catch(NumberFormatException e){System.out.println("ERROR: Enter a whole number.");}}} private double decimal(String p){while(true){try{return Double.parseDouble(text(p));}catch(NumberFormatException e){System.out.println("ERROR: Enter a number.");}}}
    private void header(String value){System.out.println("\n========================================\n"+value+"\n========================================");} private void error(Exception e){System.out.println("ERROR: "+e.getMessage());}
}
