package com.studentmanagement.repository;
import com.studentmanagement.exception.*; import com.studentmanagement.model.*; import com.studentmanagement.utility.FileManager; import java.nio.file.Path; import java.util.*;
/** Persists courses, enrollments, marks, and attendance in their required CSV files. */
public class AcademicRepository {
    private final Path coursesFile,enrollmentsFile,marksFile,attendanceFile; private final Map<String,Course> courses=new LinkedHashMap<>(); private final Set<Enrollment> enrollments=new LinkedHashSet<>(); private final Map<String,AcademicRecord> records=new LinkedHashMap<>();
    public AcademicRepository(Path dir){coursesFile=dir.resolve("courses.csv");enrollmentsFile=dir.resolve("enrollments.csv");marksFile=dir.resolve("marks.csv");attendanceFile=dir.resolve("attendance.csv");load();}
    private String key(String s,String c){return s+"\u0000"+c;}
    private void load(){for(String[]r:FileManager.readCsv(coursesFile,5))courses.put(r[0],new Course(r[0],r[1],Integer.parseInt(r[2]),r[3],Integer.parseInt(r[4])));for(String[]r:FileManager.readCsv(enrollmentsFile,2))enrollments.add(new Enrollment(r[0],r[1]));Map<String,double[]> marks=new HashMap<>();for(String[]r:FileManager.readCsv(marksFile,5))marks.put(key(r[0],r[1]),new double[]{Double.parseDouble(r[2]),Double.parseDouble(r[3]),Double.parseDouble(r[4])});Map<String,int[]> attendance=new HashMap<>();for(String[]r:FileManager.readCsv(attendanceFile,4))attendance.put(key(r[0],r[1]),new int[]{Integer.parseInt(r[2]),Integer.parseInt(r[3])});for(Enrollment e:enrollments){double[]m=marks.getOrDefault(key(e.studentId(),e.courseCode()),new double[3]);int[]a=attendance.getOrDefault(key(e.studentId(),e.courseCode()),new int[2]);records.put(key(e.studentId(),e.courseCode()),new AcademicRecord(e.studentId(),e.courseCode(),m[0],m[1],m[2],a[0],a[1]));}}
    public List<Course> courses(){return new ArrayList<>(courses.values());} public Optional<Course> course(String c){return Optional.ofNullable(courses.get(c));}
    public void addCourse(Course c){if(courses.containsKey(c.getCode()))throw new InvalidDataException("Course "+c.getCode()+" already exists.");courses.put(c.getCode(),c);save();} public void updateCourse(Course c){if(!courses.containsKey(c.getCode()))throw new CourseNotFoundException(c.getCode());courses.put(c.getCode(),c);save();}
    public void deleteCourse(String code){if(courses.remove(code)==null)throw new CourseNotFoundException(code);enrollments.removeIf(e->e.courseCode().equals(code));records.entrySet().removeIf(e->e.getValue().getCourseCode().equals(code));save();}
    public Set<Enrollment> enrollments(){return new LinkedHashSet<>(enrollments);} public void enroll(String s,String c){Enrollment e=new Enrollment(s,c);if(!enrollments.add(e))throw new DuplicateEnrollmentException(s,c);records.put(key(s,c),new AcademicRecord(s,c,0,0,0,0,0));save();}
    public void unenroll(String s,String c){Enrollment e=new Enrollment(s,c);if(!enrollments.remove(e))throw new InvalidDataException("Enrollment does not exist.");records.remove(key(s,c));save();}
    public void removeStudentData(String studentId){enrollments.removeIf(e->e.studentId().equals(studentId));records.entrySet().removeIf(e->e.getValue().getStudentId().equals(studentId));save();}
    public Optional<AcademicRecord> record(String s,String c){return Optional.ofNullable(records.get(key(s,c)));} public List<AcademicRecord> records(){return new ArrayList<>(records.values());}
    public void save(){FileManager.writeCsv(coursesFile,courses.values().stream().map(c->new String[]{c.getCode(),c.getName(),String.valueOf(c.getCredits()),c.getFacultyName(),String.valueOf(c.getMaximumMarks())}).toList());FileManager.writeCsv(enrollmentsFile,enrollments.stream().map(e->new String[]{e.studentId(),e.courseCode()}).toList());FileManager.writeCsv(marksFile,records.values().stream().map(r->new String[]{r.getStudentId(),r.getCourseCode(),String.valueOf(r.getAssignment()),String.valueOf(r.getMidterm()),String.valueOf(r.getFinalExam())}).toList());FileManager.writeCsv(attendanceFile,records.values().stream().map(r->new String[]{r.getStudentId(),r.getCourseCode(),String.valueOf(r.getClassesConducted()),String.valueOf(r.getClassesAttended())}).toList());}
}
